### PR TITLE
Fix: __toString ReflectionType deprecation

### LINKED ISSUE #82: Exception: Function ReflectionType::__toString() is deprecated
image
image

### PR DESCRIPTION
**Pull request by ReeceM**
This PR will resolve the issue of the deprecated `__toString()` method on the `ReflectionType::class`.

This would fix #82.

The solution implemented is to account for versions of PHP where this package will be used, as the method is deprecated from version 7.1 and up, yet the method call that replaces it is not available in versions below that.

For this reason I have added a version check to switch between either calling the method `getName()` or casting the name with `__toString()`, this is done to be explicit about which method we calling.

Then the rest of the functionality remains the same, if there is a type that is `int, float, bool` the defaults from the maileclipse package will be returned to give the knowledge that the constructor params worked.

If they aren't they will be mocked to an object that will then be returned.

### Side note
I also changed the variable names so they weren't so vague and represented the data we were working with.

### CODE REVIEW

**Comment by Qoraiche** [comment]
Thank you @ReeceM

File: src/mailEclipse.php [hunk 1]
```diff
@@ -655,15 +655,26 @@ private static function getMissingParams($arg, $params)
...
+         * getName() is undocumented alternative to casting to string.
+         * https://www.php.net/manual/en/class.reflectiontype.php#124658
+         *
+         * @var \ReflectionType $reflection
          */
-        $argType = (string) collect($params)->where('name', $arg)->first()->getType();
+        $reflection = collect($params)->where('name', $arg)->first()->getType();
 
-        $argType = self::TYPES[$argType] ?? null;
+        if (version_compare(phpversion(), '7.1', '>=')) {
```
Comment (4n70w4) [inline src/mailEclipse.php:665]: Why is this condition?

Comment (ReeceM) [reply src/mailEclipse.php:665]: Hi @4n70w4, are you talking about the version compare?

Comment (ReeceM) [reply src/mailEclipse.php:665]: What that is there for is one of the methods are available on php versions below 7.1, the `__toString()` on `ReflectionType`, this was replace by `getName()` on the same class, but not documented, and only available over PHP version 7.1. 

Also `ReflectionNameType` isn't always returned from my testing when making the change, `ReflectionType was the most consistent, I recall when it was a `ReflectionNamedType` it was something that wasn't going to be any point in passing to Mocker.
